install: npm ci --no-audit
jobs:
  include:
  - node_js: lts/*
    script:
    - npm test
    env: Runs the tests on node.js LTS.
    after_success:
    - npm run coveralls
  - node_js: node
    script:
    - npm test
    env: Runs the tests on node.js Stable.
    after_success:
    - npm run coveralls
  - node_js: node
    script:
      - npm run test:simd
    env: Runs simd tests on node.js Stable.

